### ISSUE TITLE
upload size exceeded

### ISSUE THREAD

**Issue by bwynants** [ingresspub/ingress.data.gdpr#3]
Resolved [org.springframework.web.mult
ipart.MaxUploadSizeExceededException: Maximum upload size exceeded; nested exception is java.lang.IllegalStateException: org.apache.tom
cat.util.http.fileupload.FileUploadBase$SizeLimitExceededException: the request was rejected because its size (32369432) exceeds the co
nfigured maximum (20971520)] to ModelAndView: reference to view with name 'redirect:/'; model is {}

**Comment by bwynants** [comment]
can i change this property on the docker?

**Comment by SgrAlpha** [comment]
Now the zip file goes over 20MB?!

Try change JAVA_OPTS in docker-compose to `"-Dspring.profiles.active=prod -Dspring.servlet.multipart.max-file-size=50MB -Dspring.servlet.multipart.max-request-size=50MB"`

**Comment by bwynants** [comment]
without -Dspring.profiles.active=prod it's parsing now

**Comment by SgrAlpha** [comment]
Good to know, `-Dspring.profiles.active=prod` is for the docker-compose using standalone database server.
